server:
  port: 8081
  servlet:
    contextPath: '/'
    application-display-name: 'mini-agro-backend'

springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jsvariedades
    username: root
    password: pass_platform_login
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true