spring:
  application:
    name: jsvariedades
  datasource:
    url: jdbc:mysql://localhost:3307/jsvariedades
    username: root
    password: jsvariedades
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true