server:
  port: 8081
  servlet:
    contextPath: '/'
    application-display-name: 'js-variedades-backend'

springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true