server:
  port: 8081
  servlet:
    contextPath: '/'
    application-display-name: 'js-variedades-backend'

springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true

spring:
  flyway:
    url: jdbc:mysql://localhost:3307/jsvariedades
    password: jsvariedades
    user: root
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:3307/jsvariedades
    username: root
    password: jsvariedades
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true